// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpccrudserver.proto;

public interface SumaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Suma)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 A = 1;</code>
   */
  int getA();

  /**
   * <code>int32 B = 2;</code>
   */
  int getB();
}
