// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpccrudserver.proto;

public interface UserRestProtoCollOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserRestProtoColl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UserRestProto user_rest_protos = 1;</code>
   */
  java.util.List<com.grpccrudserver.proto.UserRestProto> 
      getUserRestProtosList();
  /**
   * <code>repeated .UserRestProto user_rest_protos = 1;</code>
   */
  com.grpccrudserver.proto.UserRestProto getUserRestProtos(int index);
  /**
   * <code>repeated .UserRestProto user_rest_protos = 1;</code>
   */
  int getUserRestProtosCount();
  /**
   * <code>repeated .UserRestProto user_rest_protos = 1;</code>
   */
  java.util.List<? extends com.grpccrudserver.proto.UserRestProtoOrBuilder> 
      getUserRestProtosOrBuilderList();
  /**
   * <code>repeated .UserRestProto user_rest_protos = 1;</code>
   */
  com.grpccrudserver.proto.UserRestProtoOrBuilder getUserRestProtosOrBuilder(
      int index);
}
